### ISSUE TITLE
Remove/Transfer Google Analytics Integration

### ISSUE THREAD

**Issue by benjiao** [phl-microsat-dpad/image-browser#15]

**Comment by benjiao** [comment]
@rukku Do we still need this? I can either comment it out or setup our own, we are still currently passing data to Libra's analytics dashboard.

**Comment by rukku** [comment]
@benjiao Best to set up our own. Pinopollute pala natin analytics nila. :boom:

**Comment by benjiao** [comment]
@rukku oks! oo nga e. hehe

**Comment by benjiao** [comment]
done in commit #16
